# -*- coding: utf-8 -*-
"""Calculadora de FIIs - Site

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJZKWn0eyENy0W6SdcthsqUMy6-msvgy
"""

import os, re, io, json, time, logging, warnings
import datetime as dt
from typing import Dict, List, Optional, Tuple
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
from sklearn.isotonic import IsotonicRegression
from sklearn.metrics import (
    brier_score_loss, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
)
import matplotlib.pyplot as plt
import streamlit as st
from concurrent.futures import ThreadPoolExecutor, as_completed

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger("FII")
logger.setLevel(logging.INFO)

# Suprime logs de bibliotecas externas
for lib in ["yfinance", "urllib3", "requests", "pandas_datareader", "investpy"]:
    logging.getLogger(lib).setLevel(logging.CRITICAL)
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/122.0 Safari/537.36"
}

st.set_page_config(page_title="Recomendador de FIIs com Rede Bayesiana", layout="wide")
st.markdown(
    """
    <style>
    .watermark-luidy {
        position: fixed;
        bottom: 8px;
        right: 14px;
        font-size: 12px;
        color: rgba(150, 150, 150, 0.55);
        z-index: 9999;
        pointer-events: none;
        user-select: none;
    }
    </style>
    <div class="watermark-luidy">Criado por Luidy Senra</div>
    """,
    unsafe_allow_html=True,
)

# ============================================================
# LISTA DE FIIs E DADOS ESTÁTICOS (fallback caso a busca dinâmica falhe)
# ============================================================
STATIC_TICKERS = [
    "HGLG11","KNRI11","XPML11","VISC11","BTLG11","MXRF11","CPTS11","RBRR11",
    "RBRF11","HFOF11","KNCR11","IRDM11","BRCO11","RECR11","SNCI11","XPSF11",
    "VRTA11","TGAR11","VSLH11","BCRI11","RZAK11","VINO11","RZTR11","SARE11",
    "ALZR11","BARI11","BCFF11","BMLC11","BRCR11","BTAL11","CARE11","CEOC11",
    "CVBI11","DEVA11","FIIB11","FINF11","GARE11","HABT11","HCTR11","HSLG11",
    "HGRU11","HGRE11","HGBS11","HGPO11","HGRS11","IDGR11","IFIX11","IRIM11",
    "JSRE11","KISU11","KNIP11","KNRE11","MALL11","MANA11","MFII11","MGFF11",
    "MORC11","MVFI11","NSLU11","PATL11","PORD11","PRSV11","RBED11","RBFF11",
    "RBBV11","RBRP11","RBRX11","RECT11","RFOF11","RMAI11","SADI11","SCPF11",
    "SDIL11","SEQR11","SHPH11","SPTW11","TBOF11","TEPP11","TFOF11","URPR11",
    "VCJR11","VGHF11","VGIP11","VGIR11","VILG11","VOTS11","VTRT11","WTSP11",
    "XPCI11","XPCM11","XPLG11","XPIN11","XPPR11","YCHY11","ZAVI11",
]

STATIC_FUNDAMENTALS = {
    "HGLG11": {"Preco": 145.11, "P/VP": 1.02, "DY": 7.8, "Vacancia": 5.2, "Liquidez": 8.5, "Segmento": "Logístico"},
    "KNRI11": {"Preco": 149.12, "P/VP": 1.10, "DY": 7.1, "Vacancia": 3.5, "Liquidez": 6.0, "Segmento": "Híbrido"},
    "XPML11": {"Preco": 100.84, "P/VP": 1.00, "DY": 8.5, "Vacancia": 6.0, "Liquidez": 12.0, "Segmento": "Shopping"},
    "VISC11": {"Preco": 101.07, "P/VP": 1.05, "DY": 7.5, "Vacancia": 5.0, "Liquidez": 5.2, "Segmento": "Shopping"},
    "BTLG11": {"Preco": 98.31, "P/VP": 0.98, "DY": 8.0, "Vacancia": 4.8, "Liquidez": 4.5, "Segmento": "Logístico"},
    "MXRF11": {"Preco": 9.24, "P/VP": 0.90, "DY": 11.2, "Vacancia": 7.5, "Liquidez": 9.8, "Segmento": "Recebíveis"},
    "CPTS11": {"Preco": 7.30, "P/VP": 0.85, "DY": 10.5, "Vacancia": 0.0, "Liquidez": 3.2, "Segmento": "Recebíveis"},
    "RBRR11": {"Preco": 73.00, "P/VP": 1.10, "DY": 7.0, "Vacancia": 6.5, "Liquidez": 3.8, "Segmento": "Híbrido"},
    "RBRF11": {"Preco": 6.65, "P/VP": 1.00, "DY": 7.8, "Vacancia": 5.5, "Liquidez": 2.9, "Segmento": "Fundo de Fundos"},
    "HFOF11": {"Preco": 6.12, "P/VP": 0.95, "DY": 8.7, "Vacancia": 6.2, "Liquidez": 2.0, "Segmento": "Fundo de Fundos"},
    "KNCR11": {"Preco": 105.24, "P/VP": 0.98, "DY": 8.2, "Vacancia": 0.0, "Liquidez": 7.0, "Segmento": "Recebíveis"},
    "IRDM11": {"Preco": 62.40, "P/VP": 0.92, "DY": 10.0, "Vacancia": 4.5, "Liquidez": 4.0, "Segmento": "Recebíveis"},
    "BRCO11": {"Preco": 110.00, "P/VP": 1.02, "DY": 7.6, "Vacancia": 7.0, "Liquidez": 5.5, "Segmento": "Logístico"},
    "RECR11": {"Preco": 82.00, "P/VP": 0.95, "DY": 8.0, "Vacancia": 5.8, "Liquidez": 2.5, "Segmento": "Híbrido"},
    "SNCI11": {"Preco": 95.00, "P/VP": 1.00, "DY": 7.4, "Vacancia": 6.0, "Liquidez": 1.8, "Segmento": "Híbrido"},
    "XPSF11": {"Preco": 90.00, "P/VP": 0.88, "DY": 9.8, "Vacancia": 2.5, "Liquidez": 1.2, "Segmento": "Recebíveis"},
    "VRTA11": {"Preco": 105.00, "P/VP": 1.05, "DY": 7.3, "Vacancia": 4.0, "Liquidez": 6.8, "Segmento": "Logístico"},
    "TGAR11": {"Preco": 120.00, "P/VP": 1.15, "DY": 6.8, "Vacancia": 3.8, "Liquidez": 5.0, "Segmento": "Logístico"},
    "VSLH11": {"Preco": 99.00, "P/VP": 0.97, "DY": 8.8, "Vacancia": 5.5, "Liquidez": 3.0, "Segmento": "Híbrido"},
    "BCRI11": {"Preco": 57.29, "P/VP": 0.90, "DY": 10.2, "Vacancia": 0.0, "Liquidez": 2.2, "Segmento": "Recebíveis"},
    "RZAK11": {"Preco": 92.50, "P/VP": 0.93, "DY": 9.5, "Vacancia": 3.0, "Liquidez": 1.5, "Segmento": "Recebíveis"},
    "VINO11": {"Preco": 85.00, "P/VP": 1.03, "DY": 8.1, "Vacancia": 4.5, "Liquidez": 1.0, "Segmento": "Híbrido"},
    "RZTR11": {"Preco": 98.00, "P/VP": 0.99, "DY": 8.3, "Vacancia": 6.8, "Liquidez": 2.0, "Segmento": "Logístico"},
}
STATIC_FUNDAMENTALS = pd.DataFrame(STATIC_FUNDAMENTALS).T

# ============================================================
# FUNÇÕES DE COLETA (com cache)
# ============================================================
def try_get(url, timeout=15, retries=2, headers=None):
    headers = headers or HEADERS
    for _ in range(retries + 1):
        try:
            resp = requests.get(url, timeout=timeout, headers=headers, verify=False)
            if resp.status_code == 200 and resp.text.strip():
                return resp
        except Exception:
            time.sleep(1)
    return None

def _parse_br_number(x) -> float:
    """Converte números no formato brasileiro ('1.234,56' ou '8,90%') para float."""
    if x is None:
        return np.nan
    s = str(x).strip().replace("%", "").replace("\xa0", "")
    if s in ("", "-", "nan", "None"):
        return np.nan
    s = s.replace(".", "").replace(",", ".")
    try:
        return float(s)
    except ValueError:
        return np.nan

@st.cache_data(ttl=86400, show_spinner=False)
def fetch_fii_universe(max_tickers: int = 400):
    """
    Busca a lista COMPLETA de FIIs negociados na B3 (via Fundamentus) em uma única
    requisição, já com fundamentos (preço, DY, P/VP, vacância, liquidez, segmento).
    Como essa página só lista fundos atualmente negociados, fundos incorporados/
    liquidados (ex.: MORC11) somem de lá automaticamente — sem precisar manter
    uma lista estática que envelhece.
    Mantém apenas fundos com liquidez > 0 (negociados de fato) e ordena pelos
    mais líquidos primeiro, para priorizar os fundos "clássicos" (GARE11, MXRF11 etc).
    """
    try:
        resp = requests.get(
            "https://www.fundamentus.com.br/fii_resultado.php",
            headers=HEADERS, timeout=20, verify=False,
        )
        resp.encoding = "iso-8859-1"
        soup = BeautifulSoup(resp.text, "html.parser")
        table = None
        for cand in soup.find_all("table"):
            thead = cand.find("thead")
            if thead and "Papel" in thead.get_text():
                table = cand
                break
        if table is None:
            raise ValueError("Tabela de resultados não encontrada na página do Fundamentus")
        header_cells = [th.get_text(strip=True) for th in table.find("thead").find_all("th")]
        rows = []
        for tr in table.find("tbody").find_all("tr"):
            cells = [td.get_text(strip=True) for td in tr.find_all("td")]
            if len(cells) == len(header_cells):
                rows.append(cells)
        raw = pd.DataFrame(rows, columns=header_cells)
    except Exception as e:
        logger.warning(f"Falha ao buscar universo de FIIs no Fundamentus: {e}")
        tickers = sorted(set([t.upper() for t in STATIC_TICKERS if isinstance(t, str) and t.endswith("11")]))
        return tickers[:max_tickers], STATIC_FUNDAMENTALS.copy()


    raw.columns = [str(c).strip() for c in raw.columns]
    col_map = {
        "Papel": "Ticker", "Segmento": "Segmento", "Cotação": "Preco",
        "Dividend Yield": "DY", "P/VP": "P/VP", "Liquidez": "Liquidez",
        "Vacância Média": "Vacancia",
    }
    faltando = [c for c in col_map if c not in raw.columns]
    if faltando:
        logger.warning(f"Colunas ausentes no Fundamentus: {faltando}")
        tickers = sorted(set([t.upper() for t in STATIC_TICKERS if isinstance(t, str) and t.endswith("11")]))
        return tickers[:max_tickers], STATIC_FUNDAMENTALS.copy()

    df = raw[list(col_map.keys())].rename(columns=col_map)
    df["Ticker"] = df["Ticker"].astype(str).str.strip().str.upper()
    for col in ["Preco", "DY", "P/VP", "Liquidez", "Vacancia"]:
        df[col] = df[col].apply(_parse_br_number)

    # Só fundos "clássicos" (código termina em 11, exclui frações/direitos como 11B)
    df = df[df["Ticker"].str.match(r"^[A-Z]{4}11$")]
    # Só fundos com liquidez > 0, ou seja, negociados de fato (exclui fundos "fantasmas"/sem giro)
    df = df[df["Liquidez"].fillna(0) > 0]
    df = df.drop_duplicates(subset="Ticker").sort_values("Liquidez", ascending=False)
    df["Liquidez"] = df["Liquidez"] / 1_000_000  # padroniza em R$ milhões, como o resto do app espera

    df = df.head(max_tickers)
    tickers = df["Ticker"].tolist()
    fundamentals = df.set_index("Ticker")[["Preco", "P/VP", "DY", "Vacancia", "Liquidez", "Segmento"]]
    logger.info(f"Universo de FIIs coletado: {len(tickers)} fundos ativos e líquidos")
    return tickers, fundamentals

@st.cache_data(ttl=86400, show_spinner=False)
def fetch_bcb_series(codes: List[int], name: str) -> pd.Series:
    for code in codes:
        for fmt in ["json", "csv"]:
            url = f"https://api.bcb.gov.br/dados/serie/bcdata.sgs.{code}/dados?formato={fmt}"
            resp = try_get(url)
            if resp:
                try:
                    if fmt == "json":
                        data = resp.json()
                        if isinstance(data, dict):
                            data = [data]
                        df = pd.json_normalize(data)
                    else:
                        df = pd.read_csv(io.StringIO(resp.text), sep=';', engine='python')
                    if "data" in df.columns and "valor" in df.columns:
                        df["data"] = pd.to_datetime(df["data"], dayfirst=True, errors="coerce")
                        df["valor"] = pd.to_numeric(df["valor"].astype(str).str.replace(",", "."), errors="coerce")
                        s = df.set_index("data")["valor"].dropna().sort_index()
                        if len(s) > 1:
                            s.name = name
                            return s
                except Exception:
                    continue
    logger.warning(f"Não foi possível obter {name} do BCB. Usando série vazia.")
    return pd.Series(dtype=float, name=name)

def fetch_yahoo_chart_api(ticker: str, years: int = 12) -> pd.DataFrame:
    end = pd.Timestamp.today().normalize()
    start = end - pd.DateOffset(years=years)
    p1, p2 = int(start.timestamp()), int(end.timestamp())
    url = f"https://query1.finance.yahoo.com/v8/finance/chart/{ticker}.SA?period1={p1}&period2={p2}&interval=1d"
    resp = try_get(url, headers={"User-Agent": "Mozilla/5.0"})
    if resp:
        data = resp.json()
        if "chart" in data and "result" in data["chart"]:
            res = data["chart"]["result"][0]
            timestamps = res.get("timestamp", [])
            closes = res["indicators"]["quote"][0].get("close", [])
            volumes = res["indicators"]["quote"][0].get("volume", [])
            df = pd.DataFrame({"Date": pd.to_datetime(timestamps, unit="s"), "Close": closes, "Volume": volumes})
            df = df.dropna(subset=["Close"])
            if not df.empty:
                return df
    raise ValueError("Yahoo Chart API falhou")

def fetch_stooq_csv(ticker: str, years: int = 12) -> pd.DataFrame:
    url = f"https://stooq.com/q/d/l/?s={ticker.lower()}.sa&i=d"
    resp = try_get(url)
    if resp and not resp.text.startswith("<"):
        df = pd.read_csv(io.StringIO(resp.text))
        df.columns = [c.strip() for c in df.columns]
        df["Date"] = pd.to_datetime(df["Date"])
        start = pd.Timestamp.today().normalize() - pd.DateOffset(years=years)
        df = df[df["Date"] >= start].reset_index(drop=True)
        if not df.empty:
            return df[["Date", "Close", "Volume"]]
    raise ValueError("Stooq CSV falhou")

def fetch_yfinance_lib(ticker: str, years: int = 12) -> pd.DataFrame:
    import yfinance as yf
    data = yf.download(ticker + ".SA", period=f"{years}y", auto_adjust=False, progress=False)
    if data.empty:
        raise ValueError("yfinance vazio")
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.droplevel(1)
    data = data.reset_index()
    if "Date" not in data.columns and "Datetime" in data.columns:
        data.rename(columns={"Datetime": "Date"}, inplace=True)
    if "Adj Close" in data.columns and "Close" not in data.columns:
        data.rename(columns={"Adj Close": "Close"}, inplace=True)
    return data[["Date", "Close", "Volume"]]

def fetch_price_history(ticker: str) -> pd.DataFrame:
    methods = [
        ("Yahoo Chart", fetch_yahoo_chart_api),
        ("Stooq", fetch_stooq_csv),
        ("yfinance", fetch_yfinance_lib),
    ]
    for name, method in methods:
        try:
            df = method(ticker)
            if df is not None and len(df) > 10:
                return df
        except Exception:
            continue
    return None

@st.cache_data(ttl=86400, show_spinner=False)
def fetch_fundamental_data_fallback(tickers: List[str]) -> pd.DataFrame:
    """Usado apenas se fetch_fii_universe não conseguir dados para algum ticker."""
    dados = {}
    for t in tickers:
        if t in STATIC_FUNDAMENTALS.index:
            dados[t] = STATIC_FUNDAMENTALS.loc[t].to_dict()
        else:
            dados[t] = {"Preco": 100.0, "P/VP": 1.0, "DY": 8.0, "Vacancia": 5.0, "Liquidez": 1.0, "Segmento": "Desconhecido"}
    return pd.DataFrame(dados).T

# ============================================================
# CARREGAMENTO DOS DADOS DE MERCADO (com limite de tickers)
# ============================================================
@st.cache_data(ttl=86400, show_spinner=False)
def load_market_data(max_tickers: int = 400):
    """Coleta séries macro, universo de FIIs e preços. max_tickers limita a quantidade."""
    logger.info("Coletando séries macroeconômicas...")
    selic = fetch_bcb_series([432, 4189, 1178], "selic")
    ipca12 = fetch_bcb_series([13522], "ipca12")
    ipca_mensal = fetch_bcb_series([433], "ipca")

    # Busca o universo de FIIs ativos e líquidos direto da fonte (sem lista estática fixa)
    tickers, fundamentals_universo = fetch_fii_universe(max_tickers=max_tickers)

    logger.info(f"Coletando preços de {len(tickers)} FIIs...")
    price_hist = {}
    erros = []
    hoje = pd.Timestamp.today().normalize()
    limite_defasagem = hoje - pd.Timedelta(days=25)  # ~15-17 dias úteis sem negociar = fundo parado
    progress_bar = st.progress(0, text=f"Buscando preços de {len(tickers)} fundos... (0/{len(tickers)})")
    concluidos = 0
    with ThreadPoolExecutor(max_workers=15) as executor:
        future_to_ticker = {executor.submit(fetch_price_history, t): t for t in tickers}
        for future in as_completed(future_to_ticker):
            ticker = future_to_ticker[future]
            try:
                df = future.result()
                if df is not None and len(df) > 10 and pd.to_datetime(df["Date"]).max() >= limite_defasagem:
                    price_hist[ticker] = df
                else:
                    erros.append(ticker)
            except Exception:
                erros.append(ticker)
            concluidos += 1
            progress_bar.progress(
                concluidos / len(tickers),
                text=f"Buscando preços de fundos imobiliários... ({concluidos}/{len(tickers)})"
            )
    progress_bar.empty()

    if erros:
        logger.warning(f"Falha na coleta de preços (ou fundo sem negociação recente) para {len(erros)} FIIs: {erros[:10]}...")
    TICKERS_VALIDOS = list(price_hist.keys())
    logger.info(f"FIIs com dados reais e recentes: {len(TICKERS_VALIDOS)}")
    return selic, ipca12, ipca_mensal, price_hist, TICKERS_VALIDOS, fundamentals_universo

# ============================================================
# FEATURES E DATASET HISTÓRICO
# ============================================================
FEATURES_CONT = ["Momentum", "Volatilidade", "Liquidez"]
FEATURES_CAT = ["Regime", "Mercado"]
HORIZONS_MONTHS = [3, 12, 36, 120]
TARGET_COL = "Recomendacao"

def get_quantile_edges(series, q=4):
    try:
        jitter = series + np.random.normal(0, 1e-8, size=len(series))
        edges = pd.qcut(jitter, q=q, duplicates="drop", retbins=True)[1]
        if len(edges) < q + 1:
            edges = np.histogram_bin_edges(series, bins=q)
        return edges
    except:
        return np.histogram_bin_edges(series, bins=q)

def classify_regime(selic_val, selic_change_6m, ipca12_val):
    ipca_high = ipca12_val > 6.0
    ipca_low = ipca12_val < 4.5
    selic_rising = selic_change_6m > 0.5
    if ipca_high and selic_rising:
        return "estagflacao"
    elif (ipca_low or ipca12_val < 6.0) and not selic_rising:
        return "crescimento"
    return "neutro"

def classify_market(ret_3m, vol, vol_median):
    if ret_3m > 0.03 and vol < vol_median:
        return "bull"
    elif ret_3m < -0.03 or vol > 1.25 * vol_median:
        return "bear"
    return "neutro"

def build_historical_dataset(price_hist, selic, ipca12, ipca_mensal):
    close_pivot = pd.DataFrame({t: df.set_index("Date")["Close"] for t, df in price_hist.items()})
    volume_pivot = pd.DataFrame({t: df.set_index("Date")["Volume"] for t, df in price_hist.items()})
    close_pivot = close_pivot.sort_index().ffill()
    volume_pivot = volume_pivot.sort_index().ffill()
    close_pivot = close_pivot.dropna(thresh=max(10, int(len(price_hist)*0.5)))
    volume_pivot = volume_pivot.loc[close_pivot.index]

    daily_ret = close_pivot.pct_change(fill_method=None)
    count_valid = daily_ret.notna().sum(axis=1)
    market_daily_ret = daily_ret.mean(axis=1)
    market_daily_ret[count_valid < 5] = np.nan
    market_index = (1 + market_daily_ret.fillna(0)).cumprod()
    vol_daily = daily_ret.rolling(63).std() * np.sqrt(252)
    market_vol_daily = market_daily_ret.rolling(63).std() * np.sqrt(252)
    turnover_daily = close_pivot * volume_pivot
    liq_daily = turnover_daily.rolling(63).mean()

    try:
        monthly_close = close_pivot.resample("ME").last()
        monthly_market_index = market_index.resample("ME").last()
        monthly_vol = vol_daily.resample("ME").last()
        monthly_market_vol = market_vol_daily.resample("ME").last()
        monthly_liq = liq_daily.resample("ME").last()
    except:
        monthly_close = close_pivot.resample("M").last()
        monthly_market_index = market_index.resample("M").last()
        monthly_vol = vol_daily.resample("M").last()
        monthly_market_vol = market_vol_daily.resample("M").last()
        monthly_liq = liq_daily.resample("M").last()

    selic_monthly = selic.reindex(monthly_close.index, method="ffill")
    ipca12_monthly = ipca12.reindex(monthly_close.index, method="ffill")
    ipca_mensal_monthly = ipca_mensal.reindex(monthly_close.index, method="ffill")
    selic_change_6m = selic_monthly - selic_monthly.shift(6)

    rows = []
    for ticker in monthly_close.columns:
        for date in monthly_close.index:
            price = monthly_close.loc[date, ticker]
            if pd.isna(price):
                continue
            mom_3m = price / monthly_close[ticker].shift(3).loc[date] - 1
            vol = monthly_vol.loc[date, ticker]
            liq = monthly_liq.loc[date, ticker]
            mkt_ret_3m = monthly_market_index.loc[date] / monthly_market_index.shift(3).loc[date] - 1
            mkt_vol = monthly_market_vol.loc[date]
            selic_val = selic_monthly.loc[date]
            ipca12_val = ipca12_monthly.loc[date]
            ipca_m_val = ipca_mensal_monthly.loc[date]
            selic_chg = selic_change_6m.loc[date]
            if pd.isna(mom_3m) or pd.isna(vol) or pd.isna(liq) or pd.isna(mkt_ret_3m) or pd.isna(mkt_vol):
                continue
            if pd.isna(selic_val) or pd.isna(ipca12_val):
                continue
            regime = classify_regime(selic_val, selic_chg, ipca12_val)
            mkt_vol_median = market_vol_daily.rolling(252).median().resample("ME").last()
            mkt_cond = classify_market(mkt_ret_3m, mkt_vol, mkt_vol_median.loc[date] if date in mkt_vol_median.index else 0.20)

            row = {
                "Date": date, "Ticker": ticker, "Momentum": mom_3m,
                "Volatilidade": vol, "Liquidez": liq, "Retorno_Mercado": mkt_ret_3m,
                "Volatilidade_Mercado": mkt_vol, "Selic": selic_val, "IPCA_12M": ipca12_val,
                "IPCA_Mensal": ipca_m_val, "Regime": regime, "Mercado": mkt_cond,
            }
            for h in HORIZONS_MONTHS:
                future_price = monthly_close[ticker].shift(-h).loc[date]
                if pd.isna(future_price):
                    row[f"Future_Return_{h}M"] = np.nan
                    row[f"Risk_Free_{h}M"] = np.nan
                    row[f"Target_{h}M"] = np.nan
                else:
                    future_ret = future_price / price - 1
                    risk_free = (1 + selic_val / 100) ** (h / 12) - 1
                    row[f"Future_Return_{h}M"] = future_ret
                    row[f"Risk_Free_{h}M"] = risk_free
                    row[f"Target_{h}M"] = 1 if future_ret > risk_free else 0
            rows.append(row)

    df = pd.DataFrame(rows)
    logger.info(f"Dataset histórico gerado: {len(df)} linhas")
    return df

# ============================================================
# ARMAZENAMENTO DE INTERAÇÕES (CSV)
# ============================================================
INTERACTIONS_PATH = "user_interactions.csv"
RAW_DATASET_PATH = "fii_raw_dataset.csv"
MODEL_META_PATH = "model_meta.json"

def load_model_meta():
    if os.path.exists(MODEL_META_PATH):
        try:
            with open(MODEL_META_PATH, "r") as f:
                return json.load(f)
        except Exception:
            return {}
    return {}

def save_model_meta(meta: dict):
    try:
        with open(MODEL_META_PATH, "w") as f:
            json.dump(meta, f)
    except Exception as e:
        logger.warning(f"Não foi possível salvar metadados do modelo: {e}")

def load_interactions():
    if os.path.exists(INTERACTIONS_PATH):
        try:
            return pd.read_csv(INTERACTIONS_PATH, parse_dates=["Date_At_Rec", "Target_Date"])
        except:
            return pd.DataFrame()
    return pd.DataFrame(columns=[
        "Timestamp", "Ticker", "Capital", "Profile", "Objective", "Horizon_Months",
        "Price_At_Rec", "Date_At_Rec", "Target_Date", "Predicted_Prob",
        "Recommended", "Actual_Return", "Risk_Free_Return", "Outcome", "Evaluated"
    ])

def save_interactions(df):
    try:
        df.to_csv(INTERACTIONS_PATH, index=False)
        logger.info(f"Interações salvas: {len(df)}")
    except Exception as e:
        logger.warning(f"Não foi possível salvar interações: {e}")

def load_raw_dataset():
    if os.path.exists(RAW_DATASET_PATH):
        try:
            return pd.read_csv(RAW_DATASET_PATH, parse_dates=["Date"])
        except:
            return pd.DataFrame()
    return pd.DataFrame()

def save_raw_dataset(df):
    try:
        df.to_csv(RAW_DATASET_PATH, index=False)
        logger.info(f"Dataset bruto salvo: {len(df)} linhas")
    except Exception as e:
        logger.warning(f"Não foi possível salvar dataset: {e}")

def get_price_on_date(ticker, date, price_hist):
    df = price_hist.get(ticker)
    if df is None:
        return None
    df = df[df["Date"] <= date]
    if df.empty:
        return None
    return df["Close"].iloc[-1]

def evaluate_matured_interactions(interactions, price_hist, selic):
    today = pd.Timestamp.today().normalize()
    if interactions.empty:
        return interactions
    for idx, row in interactions.iterrows():
        if row["Evaluated"]:
            continue
        target_date = row["Target_Date"]
        if target_date <= today:
            ticker = row["Ticker"]
            rec_date = row["Date_At_Rec"]
            price_rec = row["Price_At_Rec"]
            price_target = get_price_on_date(ticker, target_date, price_hist)
            if price_target is None:
                df = price_hist.get(ticker)
                if df is not None and not df.empty:
                    if df["Date"].max() >= target_date:
                        price_target = df[df["Date"] >= target_date]["Close"].iloc[0]
                    else:
                        continue
            if price_target is None:
                continue
            actual_ret = price_target / price_rec - 1
            selic_at_rec = selic.reindex(pd.Index([rec_date]), method="ffill")
            if len(selic_at_rec) > 0 and not pd.isna(selic_at_rec.iloc[0]):
                selic_val = selic_at_rec.iloc[0]
            else:
                selic_val = 0.0
            h = row["Horizon_Months"]
            risk_free = (1 + selic_val / 100) ** (h / 12) - 1
            outcome = 1 if actual_ret > risk_free else 0
            interactions.at[idx, "Actual_Return"] = actual_ret
            interactions.at[idx, "Risk_Free_Return"] = risk_free
            interactions.at[idx, "Outcome"] = outcome
            interactions.at[idx, "Evaluated"] = True
            logger.info(f"Avaliada interação {ticker} de {rec_date.date()} -> {target_date.date()} | Retorno {actual_ret:.2%} | Outcome {outcome}")
    return interactions

def merge_feedback_into_raw(raw, interactions, price_hist):
    if interactions.empty or raw.empty:
        return raw
    feedback = interactions[interactions["Evaluated"]].copy()
    if feedback.empty:
        return raw
    for h in HORIZONS_MONTHS:
        col = f"Target_{h}M"
        if col not in raw.columns:
            raw[col] = np.nan
        raw[col] = pd.to_numeric(raw[col], errors="coerce")
    for _, row in feedback.iterrows():
        ticker = row["Ticker"]
        rec_date = row["Date_At_Rec"]
        h = row["Horizon_Months"]
        outcome = row["Outcome"]
        mask = (raw["Ticker"] == ticker) & (raw["Date"] == rec_date)
        if mask.any():
            raw.loc[mask, f"Target_{h}M"] = outcome
    return raw

# ============================================================
# DISCRETIZAÇÃO E TREINAMENTO
# ============================================================
STATE_LABELS = {
    "Momentum": ["muito_baixo", "baixo", "alto", "muito_alto"],
    "Volatilidade": ["muito_baixa", "baixa", "alta", "muito_alta"],
    "Liquidez": ["muito_baixa", "baixa", "alta", "muito_alta"],
    "Regime": ["crescimento", "estagflacao", "neutro"],
    "Mercado": ["bull", "bear", "neutro"],
    "Recomendacao": ["nao", "sim"],
}

def discretize_dataframe_for_horizon(raw_df, edges, horizon_months):
    target_col = f"Target_{horizon_months}M"
    if target_col not in raw_df.columns:
        return pd.DataFrame()
    df = raw_df.copy()
    df = df.dropna(subset=[target_col])
    for col in FEATURES_CONT:
        labels = STATE_LABELS[col]
        df[col] = pd.cut(df[col], bins=edges[col], labels=labels, include_lowest=True)
    for col in FEATURES_CAT:
        df[col] = df[col].astype(str)
    df[TARGET_COL] = df[target_col].map({1: "sim", 0: "nao"})
    cols = ["Date", "Ticker"] + FEATURES_CONT + FEATURES_CAT + [TARGET_COL]
    return df[cols].dropna(subset=FEATURES_CONT + FEATURES_CAT + [TARGET_COL])

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import BayesianEstimator
from pgmpy.inference import VariableElimination

def build_bn_model(data):
    model = DiscreteBayesianNetwork([
        ("Regime", "Mercado"),
        ("Regime", "Recomendacao"),
        ("Mercado", "Recomendacao"),
        ("Momentum", "Recomendacao"),
        ("Volatilidade", "Recomendacao"),
        ("Liquidez", "Recomendacao"),
    ])
    nodes = FEATURES_CONT + FEATURES_CAT + [TARGET_COL]
    model.add_nodes_from(nodes)
    training_data = data[nodes].copy()
    for col in nodes:
        training_data[col] = training_data[col].astype("category")
    estimator = BayesianEstimator(model, training_data)
    for node in model.nodes():
        parents = list(model.get_parents(node))
        cpd = estimator.estimate_cpd(node, prior_type="BDeu", equivalent_sample_size=10)
        model.add_cpds(cpd)
    if not model.check_model():
        raise ValueError("Modelo inconsistente após estimação das CPDs")
    return model

def get_bn_probs(model, df):
    infer = VariableElimination(model)
    probs = []
    for _, row in df.iterrows():
        evidence = {col: row[col] for col in FEATURES_CONT + FEATURES_CAT}
        try:
            q = infer.query(variables=[TARGET_COL], evidence=evidence, show_progress=False)
            state_names = list(q.state_names[TARGET_COL])
            idx = state_names.index("sim")
            probs.append(q.values[idx])
        except Exception:
            probs.append(0.5)
    return np.array(probs)

def train_models_for_all_horizons(raw_all, edges):
    models = {}
    calibrations = {}
    dates_sorted = sorted(raw_all["Date"].unique())
    n = len(dates_sorted)
    if n < 10:
        st.error("Dados históricos insuficientes para treinar modelos.")
        return {}, {}
    train_dates = dates_sorted[:int(0.6*n)]
    val_dates = dates_sorted[int(0.6*n):int(0.8*n)]

    for h in HORIZONS_MONTHS:
        discrete_h = discretize_dataframe_for_horizon(raw_all, edges, h)
        if discrete_h.empty:
            continue
        train_df = discrete_h[discrete_h["Date"].isin(train_dates)]
        val_df = discrete_h[discrete_h["Date"].isin(val_dates)]
        if train_df.empty or val_df.empty:
            continue
        try:
            model_eval = build_bn_model(train_df)
            val_probs = get_bn_probs(model_eval, val_df)
            calib_model = IsotonicRegression(out_of_bounds="clip")
            y_val = val_df[TARGET_COL].map({"sim": 1, "nao": 0}).values
            calib_model.fit(val_probs, y_val)
            final_model = build_bn_model(discrete_h)
            models[h] = final_model
            calibrations[h] = calib_model
        except Exception as e:
            logger.warning(f"Falha ao treinar modelo para horizonte {h}M: {e}")
    return models, calibrations

def get_current_predictions(models, calibrations, current_discrete, horizon_months):
    if horizon_months not in models:
        return 0.5
    probs = get_bn_probs(models[horizon_months], current_discrete)
    if horizon_months in calibrations:
        probs = calibrations[horizon_months].predict(probs)
    return probs

# ============================================================
# SIMULAÇÃO MONTE CARLO E SCORE DE ADEQUAÇÃO
# ============================================================
def project_price_monte_carlo(current_price, base_prob, vol_annual, months=12, n_sim=2000, seed=42):
    rng = np.random.default_rng(seed)
    sigma_m = vol_annual / np.sqrt(12)
    annual_drift = (base_prob - 0.5) * 0.30
    drift_m = annual_drift / 12
    scenarios = {
        "bull": {"prob": 0.35, "drift": 0.010},
        "neutral": {"prob": 0.40, "drift": 0.000},
        "bear": {"prob": 0.25, "drift": -0.015},
    }
    expected_prices = []
    prob_neg_components = []
    for scen in scenarios.values():
        scen_drift = drift_m + scen["drift"]
        z = rng.normal(size=(n_sim, months))
        monthly_ret = scen_drift + sigma_m * z
        price_paths = current_price * np.exp(np.cumsum(monthly_ret, axis=1))
        final_prices = price_paths[:, -1]
        expected_prices.append(scen["prob"] * np.mean(final_prices))
        prob_neg_components.append(scen["prob"] * np.mean(final_prices < current_price))
    expected_price = np.sum(expected_prices)
    prob_neg_total = np.sum(prob_neg_components)
    ret_esperado = expected_price / current_price - 1
    return expected_price, ret_esperado, prob_neg_total

def adjust_score(row, current_df, profile, objective, horizon):
    base = row["Base_Prob"]
    pct_vol = current_df["Volatilidade"].rank(pct=True).loc[row.name]
    pct_mom = current_df["Momentum"].rank(pct=True).loc[row.name]
    pct_liq = current_df["Liquidez"].rank(pct=True).loc[row.name]
    pct_dy = current_df["DY"].rank(pct=True).loc[row.name]
    pct_pvp = current_df["P/VP"].rank(pct=True).loc[row.name]
    pct_vac = current_df["Vacancia"].rank(pct=True).loc[row.name]

    adj = 0.0
    if objective == "renda":
        adj += 0.15 * pct_dy + 0.05 * (1 - pct_vac)
    elif objective == "valorização":
        adj += 0.10 * pct_mom + 0.10 * (1 - pct_pvp)
    elif objective == "equilíbrio":
        adj += 0.05 * pct_dy + 0.05 * pct_mom

    if profile == "conservador":
        adj -= 0.15 * pct_vol
    elif profile == "moderado":
        adj -= 0.05 * pct_vol
    elif profile == "agressivo":
        adj += 0.10 * pct_vol

    if horizon == "curto":
        adj -= 0.10 * pct_vol + 0.10 * (1 - pct_liq)
    elif horizon == "longo":
        adj += 0.05 * pct_vol

    return float(np.clip(base + adj, 0, 1))

# ============================================================
# FUNÇÃO PRINCIPAL DO APP
# ============================================================
def main():
    st.sidebar.header("🔍 Parâmetros da Análise")
    capital = st.sidebar.number_input(
        "Capital para investir (R$)", min_value=100.0, value=10000.0, step=1.0, format="%.2f"
    )
    patrimonio_total = st.sidebar.number_input(
        "Patrimônio total (opcional, R$)", min_value=0.0, value=0.0, step=1.0, format="%.2f",
        help="Usado apenas para te avisar se o valor acima passa de ~25% do seu patrimônio total."
    )
    if patrimonio_total > 0:
        limite_25 = patrimonio_total * 0.25
        if capital > limite_25:
            st.sidebar.warning(
                f"⚠️ R$ {capital:,.2f} é mais do que 25% do seu patrimônio informado "
                f"(R$ {limite_25:,.2f}). O recomendado geralmente é destinar **até ~25%** "
                "do patrimônio total a FIIs, para manter diversificação com outras classes de ativo."
            )
    else:
        st.sidebar.caption("💡 Regra geral: destine no máximo ~25% do seu patrimônio total a FIIs.")

    profile = st.sidebar.selectbox("Perfil do investidor", ["conservador", "moderado", "agressivo"], index=1)
    objective = st.sidebar.selectbox("Objetivo", ["renda", "valorização", "equilíbrio"], index=0)

    st.sidebar.markdown("**Horizonte de investimento**")
    unidade_horizonte = st.sidebar.radio("Unidade", ["Meses", "Anos"], index=1, horizontal=True, label_visibility="collapsed")
    if unidade_horizonte == "Meses":
        horizon_months = st.sidebar.number_input("Quantidade de meses", min_value=1, max_value=360, value=36, step=1)
    else:
        horizon_years = st.sidebar.number_input("Quantidade de anos", min_value=1, max_value=30, value=3, step=1)
        horizon_months = int(horizon_years * 12)

    n_fiis = st.sidebar.slider("Quantidade de FIIs no ranking", min_value=5, max_value=30, value=10, step=1)
    criterio_alocacao = st.sidebar.radio(
        "Dividir o capital por:",
        ["Adequação ao perfil", "Chance de sucesso"],
        index=0,
        help="Adequação ao perfil considera seu objetivo e tolerância a risco. "
             "Chance de sucesso olha só a probabilidade de o preço não cair no horizonte escolhido — "
             "por isso o fundo mais indicado pode não ser o de maior alocação e vice-versa."
    )
    run_button = st.sidebar.button("🚀 Executar Análise", type="primary")
    retrain_clicked = st.sidebar.button("🔄 Retreinar Modelos (busca tudo de novo)")

    meta = load_model_meta()
    if meta.get("last_trained"):
        st.sidebar.caption(f"🕒 Último treino do modelo: {meta['last_trained']}")
    else:
        st.sidebar.caption("🕒 Modelo ainda não foi treinado nesta instância.")

    if retrain_clicked:
        fetch_fii_universe.clear()
        load_market_data.clear()
        for key in ["raw_all", "models", "calibrations"]:
            st.session_state.pop(key, None)
        if os.path.exists(RAW_DATASET_PATH):
            os.remove(RAW_DATASET_PATH)

    with st.status("🔎 Estamos buscando o melhor para você...", expanded=True) as status:
        status.write("Carregando dados de mercado (Selic, IPCA, universo de FIIs e preços)...")
        selic, ipca12, ipca_mensal, price_hist, tickers_validos, fundamentals_universo = load_market_data(max_tickers=400)
        status.write(f"✅ Dados de mercado obtidos para {len(tickers_validos)} fundos ativos e líquidos.")

        if "raw_all" not in st.session_state:
            raw_file = load_raw_dataset()
            if raw_file.empty:
                status.write("Construindo base histórica (isso só acontece na primeira vez ou após retreinar)...")
                raw_all = build_historical_dataset(price_hist, selic, ipca12, ipca_mensal)
                save_raw_dataset(raw_all)
            else:
                raw_all = raw_file
            st.session_state.raw_all = raw_all
        else:
            raw_all = st.session_state.raw_all
        status.update(label="✅ Dados de mercado prontos", state="complete", expanded=False)

    interactions = load_interactions()
    if not interactions.empty:
        interactions = evaluate_matured_interactions(interactions, price_hist, selic)
        save_interactions(interactions)
        raw_all = merge_feedback_into_raw(raw_all, interactions, price_hist)
        save_raw_dataset(raw_all)
        st.session_state.raw_all = raw_all

    dates_sorted = sorted(raw_all["Date"].unique())
    cutoff_date = dates_sorted[int(0.8 * len(dates_sorted))]
    train_for_bins = raw_all[raw_all["Date"] <= cutoff_date]
    edges = {col: get_quantile_edges(train_for_bins[col], q=4) for col in FEATURES_CONT}

    if "models" not in st.session_state:
        with st.status("🧠 Treinando as redes bayesianas...", expanded=True) as status:
            status.write("Isso analisa o histórico de todos os fundos para aprender padrões de risco e retorno.")
            models, calibrations = train_models_for_all_horizons(raw_all, edges)
            st.session_state.models = models
            st.session_state.calibrations = calibrations
            agora_str = pd.Timestamp.now().strftime("%d/%m/%Y às %H:%M")
            save_model_meta({"last_trained": agora_str, "n_fiis_universo": len(tickers_validos)})
            status.update(label="✅ Modelos treinados", state="complete", expanded=False)
    models = st.session_state.models
    calibrations = st.session_state.calibrations

    if not models:
        st.error("Não foi possível treinar nenhum modelo. Verifique os dados.")
        return

    # Fundamentos já vieram junto com o universo de FIIs (uma única requisição);
    # só precisamos buscar via fallback caso algum ticker válido tenha ficado de fora.
    faltantes = [t for t in tickers_validos if t not in fundamentals_universo.index]
    if faltantes:
        fallback_df = fetch_fundamental_data_fallback(faltantes)
        fundamental_df = pd.concat([fundamentals_universo, fallback_df])
    else:
        fundamental_df = fundamentals_universo
    fundamental_df = fundamental_df.loc[tickers_validos]

    current_raw = raw_all[raw_all["Ticker"].isin(tickers_validos)].sort_values("Date").groupby("Ticker").tail(1).copy()
    current_raw = current_raw.set_index("Ticker")

    missing = set(tickers_validos) - set(current_raw.index)
    if missing:
        median_vals = current_raw[FEATURES_CONT].median()
        mode_vals = current_raw[FEATURES_CAT].mode().iloc[0]
        for t in missing:
            current_raw.loc[t] = {
                "Date": current_raw["Date"].max(),
                "Momentum": median_vals["Momentum"],
                "Volatilidade": median_vals["Volatilidade"],
                "Liquidez": median_vals["Liquidez"],
                "Retorno_Mercado": current_raw["Retorno_Mercado"].median(),
                "Volatilidade_Mercado": current_raw["Volatilidade_Mercado"].median(),
                "Selic": current_raw["Selic"].median(),
                "IPCA_12M": current_raw["IPCA_12M"].median(),
                "IPCA_Mensal": current_raw["IPCA_Mensal"].median(),
                "Regime": mode_vals["Regime"],
                "Mercado": mode_vals["Mercado"],
            }

    current_discrete = pd.DataFrame(index=current_raw.index)
    for col in FEATURES_CONT:
        current_discrete[col] = pd.cut(
            current_raw[col].clip(edges[col][0], edges[col][-1]),
            bins=edges[col], labels=STATE_LABELS[col], include_lowest=True
        )
    for col in FEATURES_CAT:
        current_discrete[col] = current_raw[col].apply(
            lambda x: x if x in STATE_LABELS[col] else STATE_LABELS[col][-1]
        )

    # BN foi treinado apenas para horizontes fixos (3, 12, 36, 120 meses);
    # usamos o modelo mais próximo do horizonte livre escolhido pelo usuário.
    bn_horizon_months = min(HORIZONS_MONTHS, key=lambda h: abs(h - horizon_months))
    bn_probs = get_current_predictions(models, calibrations, current_discrete, bn_horizon_months)

    # Bucket textual do horizonte, usado apenas para ajustar o score por perfil/objetivo
    if horizon_months <= 18:
        horizon = "curto"
    elif horizon_months <= 72:
        horizon = "médio"
    else:
        horizon = "longo"

    fund_percentiles = pd.DataFrame({
        "pct_pvp": fundamental_df["P/VP"].rank(pct=True),
        "pct_dy": fundamental_df["DY"].rank(pct=True),
        "pct_vac": fundamental_df["Vacancia"].rank(pct=True),
        "pct_liq": fundamental_df["Liquidez"].rank(pct=True),
    })
    score_fund = (0.25*(1-fund_percentiles["pct_pvp"]) + 0.35*fund_percentiles["pct_dy"] +
                  0.20*(1-fund_percentiles["pct_vac"]) + 0.20*fund_percentiles["pct_liq"]).clip(0,1)

    base_prob = (0.7*bn_probs + 0.3*score_fund).clip(0,1)

    preco_mercado = {t: price_hist[t]["Close"].iloc[-1] for t in tickers_validos}

    current_df = pd.DataFrame(index=tickers_validos)
    current_df["Preco"] = [preco_mercado[t] for t in tickers_validos]
    current_df["P/VP"] = fundamental_df["P/VP"]
    current_df["DY"] = fundamental_df["DY"]
    current_df["Vacancia"] = fundamental_df["Vacancia"]
    current_df["Liquidez"] = fundamental_df["Liquidez"]
    current_df["Segmento"] = fundamental_df["Segmento"]
    current_df["Momentum"] = current_raw["Momentum"]
    current_df["Volatilidade"] = current_raw["Volatilidade"]
    current_df["BN_Prob"] = bn_probs
    current_df["Score_Fund"] = score_fund
    current_df["Base_Prob"] = base_prob

    scores = current_df.apply(lambda r: adjust_score(r, current_df, profile, objective, horizon), axis=1)
    current_df["Adequação"] = scores
    current_df = current_df.sort_values("Adequação", ascending=False)

    top_df = current_df.head(n_fiis).copy()

    projections = []
    for t in top_df.index:
        price = top_df.loc[t, "Preco"]
        vol = top_df.loc[t, "Volatilidade"]
        bp = top_df.loc[t, "Base_Prob"]
        exp_price, ret_esp, prob_neg = project_price_monte_carlo(price, bp, vol, months=horizon_months)
        projections.append({
            "Ticker": t,
            "Preco_Projetado": exp_price,
            "Retorno_Esperado": ret_esp,
            "Prob_Queda": prob_neg,
        })
    proj_df = pd.DataFrame(projections).set_index("Ticker")
    top_df = top_df.join(proj_df)
    top_df["Div_Anual_Estimado"] = top_df["Preco"] * top_df["DY"] / 100
    top_df["Chance_Sucesso"] = 1 - top_df["Prob_Queda"]

    # Aloca o capital do usuário proporcionalmente ao critério escolhido na barra lateral.
    # Depois converte para nº de cotas inteiras (arredondando pra baixo) ao preço atual.
    coluna_peso = "Adequação" if criterio_alocacao == "Adequação ao perfil" else "Chance_Sucesso"
    peso = top_df[coluna_peso].clip(lower=0)
    if peso.sum() > 0:
        peso = peso / peso.sum()
    else:
        peso = pd.Series(1 / len(top_df), index=top_df.index)
    top_df["Valor_Alocado"] = peso * capital
    top_df["Cotas_Estimadas"] = np.floor(top_df["Valor_Alocado"] / top_df["Preco"]).astype(int)
    top_df["Valor_Alocado"] = top_df["Cotas_Estimadas"] * top_df["Preco"]

    display_df = top_df[[
        "Segmento", "Preco", "P/VP", "DY", "Vacancia", "Liquidez",
        "Div_Anual_Estimado", "Adequação", "Valor_Alocado", "Cotas_Estimadas",
        "Chance_Sucesso", "Preco_Projetado", "Retorno_Esperado", "Prob_Queda"
    ]].copy()
    display_df["Liquidez"] = display_df["Liquidez"].apply(lambda x: f"R$ {x:.2f} mi")
    display_df["DY"] = display_df["DY"].apply(lambda x: f"{x:.1f}%")
    display_df["Vacancia"] = display_df["Vacancia"].apply(lambda x: f"{x:.1f}%")
    display_df["Valor_Alocado"] = display_df["Valor_Alocado"].apply(lambda x: f"R$ {x:,.2f}")
    display_df["Chance_Sucesso"] = display_df["Chance_Sucesso"].apply(lambda x: f"{x:.1%}")
    display_df["Div_Anual_Estimado"] = display_df["Div_Anual_Estimado"].apply(lambda x: f"R$ {x:.2f}")
    display_df["Adequação"] = display_df["Adequação"].apply(lambda x: f"{x:.2%}")
    display_df["Retorno_Esperado"] = display_df["Retorno_Esperado"].apply(lambda x: f"{x:+.2%}")
    display_df["Prob_Queda"] = display_df["Prob_Queda"].apply(lambda x: f"{x:.2%}")
    display_df["Preco_Projetado"] = display_df["Preco_Projetado"].apply(lambda x: f"R$ {x:.2f}")
    display_df = display_df.rename(columns={
        "Preco": "Preço Atual", "Vacancia": "Vacância", "Liquidez": "Liquidez Diária",
        "Div_Anual_Estimado": "Div. Anual Estimado", "Adequação": "Adequação ao Perfil",
        "Valor_Alocado": "Valor a Investir", "Cotas_Estimadas": "Cotas",
        "Chance_Sucesso": "Chance de Sucesso", "Preco_Projetado": "Preço Projetado",
        "Retorno_Esperado": "Retorno Esperado", "Prob_Queda": "Prob. de Queda",
    })

    valor_investido_total = top_df["Valor_Alocado"].sum()
    sobra = capital - valor_investido_total

    if run_button:
        st.success(f"Análise concluída para **{profile}**, **{objective}**, horizonte **{horizon_months} meses**.")
        st.dataframe(display_df, use_container_width=True)
        st.caption(
            f"💰 Total alocado: R$ {valor_investido_total:,.2f} de R$ {capital:,.2f} "
            f"(R$ {sobra:,.2f} não alocado por arredondamento de cotas inteiras). "
            f"A divisão entre fundos é proporcional à **{criterio_alocacao}** de cada um — "
            "por isso o fundo com maior alocação nem sempre é o de maior chance de sucesso "
            "(e vice-versa), já que são critérios diferentes. Considere isso um ponto de "
            "partida, não uma recomendação definitiva."
        )

        st.markdown("#### 📝 Por que esses fundos foram indicados")
        for t in top_df.head(5).index:
            r = top_df.loc[t]
            motivos = []
            if fund_percentiles.loc[t, "pct_dy"] >= 0.7:
                motivos.append("dividend yield entre os mais altos do ranking")
            if fund_percentiles.loc[t, "pct_pvp"] <= 0.3:
                motivos.append("negociado com desconto sobre o valor patrimonial (P/VP baixo)")
            if fund_percentiles.loc[t, "pct_vac"] <= 0.3:
                motivos.append("vacância baixa em relação aos demais")
            if fund_percentiles.loc[t, "pct_liq"] >= 0.7:
                motivos.append("boa liquidez diária, facilitando compra e venda")
            if r["Retorno_Esperado"] > 0:
                motivos.append(f"projeção de valorização de {r['Retorno_Esperado']:+.1%} no horizonte escolhido")
            if not motivos:
                motivos.append("bom equilíbrio geral entre os indicadores analisados")
            st.markdown(f"**{t}** ({r['Segmento']}): " + "; ".join(motivos) + ".")
        st.caption(
            "Resumo gerado a partir dos indicadores calculados (percentis de DY, P/VP, vacância "
            "e liquidez do próprio ranking) — não é uma análise qualitativa de notícias ou fatos "
            "relevantes do fundo."
        )

        now = pd.Timestamp.now()
        target_date = now + pd.DateOffset(months=horizon_months)
        for t in top_df.index:
            row = {
                "Timestamp": now,
                "Ticker": t,
                "Capital": capital,
                "Profile": profile,
                "Objective": objective,
                "Horizon_Months": horizon_months,
                "Price_At_Rec": top_df.loc[t, "Preco"],
                "Date_At_Rec": now,
                "Target_Date": target_date,
                "Predicted_Prob": top_df.loc[t, "Base_Prob"],
                "Recommended": True,
                "Actual_Return": np.nan,
                "Risk_Free_Return": np.nan,
                "Outcome": np.nan,
                "Evaluated": False,
            }
            interactions = pd.concat([interactions, pd.DataFrame([row])], ignore_index=True)
        save_interactions(interactions)
        st.info("Suas recomendações foram armazenadas e serão avaliadas após o prazo do horizonte.")

    tab1, tab2, tab3 = st.tabs(["📊 Ranking", "🔍 Detalhes", "📈 Simulação"])

    with tab1:
        if run_button:
            st.dataframe(display_df, use_container_width=True)
        else:
            st.info("Clique em **Executar Análise** para gerar o ranking.")

    with tab2:
        fii = st.selectbox("Selecione um FII para ver detalhes", current_df.index.tolist())
        if fii:
            r = current_df.loc[fii]
            st.markdown(f"### Detalhes do FII {fii}")
            st.write(f"**Segmento:** {r['Segmento']}")
            st.write(f"**Preço atual:** R$ {r['Preco']:.2f}")
            st.write(f"**P/VP:** {r['P/VP']:.2f}")
            st.write(f"**Dividend Yield:** {r['DY']:.1f}%")
            st.write(f"**Dividendo Anual Estimado:** R$ {r['Preco'] * r['DY'] / 100:.2f}")
            st.write(f"**Vacância:** {r['Vacancia']:.1f}%")
            st.write(f"**Liquidez diária:** R$ {r['Liquidez']:.2f} milhões")
            st.write(f"**Volatilidade anualizada:** {r['Volatilidade']:.2%}")
            st.write(f"**Momentum 3m:** {r['Momentum']:.2%}")
            st.write(f"**Probabilidade base (BN+fundamentalista):** {r['Base_Prob']:.2%}")

    with tab3:
        fii_sim = st.selectbox("Selecione um FII para simular", current_df.index.tolist(), key="sim_select")
        if fii_sim:
            r = current_df.loc[fii_sim]
            price = r["Preco"]
            vol = r["Volatilidade"]
            bp = r["Base_Prob"]
            months = horizon_months
            exp_price, ret_esp, prob_neg = project_price_monte_carlo(price, bp, vol, months=months)
            sigma_m = vol / np.sqrt(12)
            drift_annual = (bp - 0.5) * 0.30
            drift_m = drift_annual / 12
            scen = {"prob": 0.35, "drift": 0.010}
            rng = np.random.default_rng(42)
            z = rng.normal(size=(1000, months))
            rets = drift_m + scen["drift"] + sigma_m * z
            final_prices = price * np.exp(np.cumsum(rets, axis=1))[:, -1]

            fig, ax = plt.subplots(figsize=(8, 4))
            ax.hist(final_prices, bins=50, alpha=0.7, color="#4da6ff")
            ax.axvline(price, color="red", linestyle="--", label="Preço atual")
            ax.axvline(exp_price, color="green", linestyle="--", label=f"Projeção média ({horizon})")
            ax.set_title(f"Distribuição de preços em {months} meses - {fii_sim} (cenário bull)")
            ax.set_xlabel("Preço projetado (R$)")
            ax.set_ylabel("Frequência")
            ax.legend()
            st.pyplot(fig)

    # ============================================================
    # CHAT COM IA — TIRE DÚVIDAS SOBRE A RECOMENDAÇÃO
    # ============================================================
    st.divider()
    st.markdown("### 💬 Converse com a IA sobre a recomendação")
    st.caption(
        "Pergunte sobre os fundos do ranking, o que significam os indicadores, "
        "ou peça para comparar dois FIIs. A IA responde com base apenas nos "
        "dados calculados acima — não é uma recomendação de investimento."
    )

    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    def montar_contexto_para_ia(top_df, profile, objective, horizon_months, criterio_alocacao):
        linhas = [
            f"Perfil do investidor: {profile}",
            f"Objetivo: {objective}",
            f"Horizonte: {horizon_months} meses",
            f"Critério de alocação escolhido: {criterio_alocacao}",
            "",
            "Ranking atual de FIIs recomendados (do melhor para o pior colocado):",
        ]
        for t in top_df.index:
            r = top_df.loc[t]
            linhas.append(
                f"- {t} ({r['Segmento']}): Preço R$ {r['Preco']:.2f}, "
                f"P/VP {r['P/VP']:.2f}, DY {r['DY']:.1f}%, Vacância {r['Vacancia']:.1f}%, "
                f"Adequação ao perfil {r['Adequação']:.1%}, "
                f"Chance de sucesso {r['Chance_Sucesso']:.1%}, "
                f"Retorno esperado {r['Retorno_Esperado']:+.1%}, "
                f"Valor a investir R$ {r['Valor_Alocado']:.2f} ({r['Cotas_Estimadas']} cotas)."
            )
        return "\n".join(linhas)

    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    pergunta = st.chat_input("Pergunte algo sobre os fundos recomendados...")
    if pergunta:
        st.session_state.chat_history.append({"role": "user", "content": pergunta})
        with st.chat_message("user"):
            st.markdown(pergunta)

        with st.chat_message("assistant"):
            with st.spinner("Pensando..."):
                try:
                    import anthropic  # import local, usado só aqui
                    api_key = st.secrets.get("ANTHROPIC_API_KEY", os.environ.get("ANTHROPIC_API_KEY"))
                    if not api_key:
                        resposta = (
                            "⚠️ Nenhuma chave de API configurada. Adicione `ANTHROPIC_API_KEY` "
                            "em Settings → Secrets no Streamlit Cloud para habilitar o chat."
                        )
                    else:
                        client = anthropic.Anthropic(api_key=api_key)
                        contexto = montar_contexto_para_ia(
                            top_df, profile, objective, horizon_months, criterio_alocacao
                        )
                        system_prompt = (
                            "Você é um assistente que ajuda o usuário a entender o ranking de "
                            "Fundos Imobiliários (FIIs) gerado pelo app dele. Responda em português, "
                            "de forma clara e objetiva, com base SOMENTE nos dados fornecidos abaixo. "
                            "Se a pergunta não puder ser respondida com esses dados, diga isso. "
                            "Nunca dê recomendação de compra/venda como certeza — deixe claro que é "
                            "uma ferramenta de apoio, não uma recomendação financeira.\n\n"
                            f"{contexto}"
                        )
                        historico_api = [
                            {"role": m["role"], "content": m["content"]}
                            for m in st.session_state.chat_history
                        ]
                        response = client.messages.create(
                            model="claude-sonnet-4-6",
                            max_tokens=1000,
                            system=system_prompt,
                            messages=historico_api,
                        )
                        resposta = "".join(
                            block.text for block in response.content if block.type == "text"
                        )
                except Exception as e:
                    resposta = f"⚠️ Não foi possível obter resposta da IA agora ({e})."

                st.markdown(resposta)
        st.session_state.chat_history.append({"role": "assistant", "content": resposta})
if __name__ == "__main__":
    main()
